apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-teste
  labels:
    app: app-teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
